### ISSUE TITLE
JsonFileNotFoundException

### ISSUE THREAD

**Issue by zeta-sis** [htmlburger/wpemerge#10]
## Version

  - WP Emerge: 0.12.0
  - WordPress: 5.0.3
  - PHP: 7.0.32

## Comments
Hi, 
after installation i got this error

```
WPEmergeTheme \ Concerns \ JsonFileNotFoundException
The required manifest.json file is missing. Please run one of the build commands to generate it.

```

**Comment by atanas-angelov-dev** [comment]
Hi @zeta-sis ,

Did you try running `yarn build`? The build step generates the `manifest.json` file used for assets.

In the next update I'll be changing it so you do not get an exception as I guess it's too jarring.

**Comment by zeta-sis** [comment]
Hi Atanas, 
`yarn` was not installed. i installed end its work.

thank you.

**Comment by atanas-angelov-dev** [comment]
Just to clarify, yarn is not required - you can use npm in the same way (e.g. `npm run build`) - it's a preference thing.

**Comment by zeta-sis** [comment]
problem is `libpng` not installed on server. after install it works well.

thank you for your help Atanas. now i can start learning wpemerge

**Comment by atanas-angelov-dev** [comment]
The exception will no longer appear once htmlburger/wpemerge-theme-core@353ffbc6f9d933792585bec548edda9a5a366740 is live.
