### ISSUE TITLE
Suggestion: An in depth tutorial for newcomers

### ISSUE THREAD

**Issue by stefanos82** [htmlburger/wpemerge#11]
This is a very interesting project, kudos!

As the title says, we definitely need a tutorial that goes in depth following step by step concept.

It would make newcomers feel more than welcome to use it, let alone embrace it.

I will take a look at it and experiment as much as possible.

Keep up the good work :+1:

**Comment by atanas-angelov-dev** [comment]
Hi @stefanos82 ,

Thank you for the feedback! Could you please share more details about what you'd imagine a tutorial like this would consist of?
Note that there are plans for a tutorial series on creating a site from scratch using the starter theme and there are occasional blog posts on specific features but I'm kind of spread thin so to speak so content output is not where I'd like it to be.

**Comment by stefanos82** [comment]
Well, what I would like to read is either a long, fully detailed tutorial that explains in great detail how this project works with its best practices and important tweaks if there any, or a series of consecutive articles that demonstrate the same thing in order to keep me engaged.

For instance, I'm interested in the following points:
- how it started
- why it started
- what problem(s) does it try to solve
- what are the best practices (its "Do"s and "Don't"s)
- which are its limits if there are any
- how does it compare to Timber plugin
- which projects, websites, or companies are using it and how they got benefited from using it
- how productive a developer can become by using this project comparing it with vanilla WP or Timber plugin
- how to migrate existing themes or WP websites to wpemerge

I cannot think of anything else right now, but I'm sure I will find other things to ask afterwards.

**Comment by atanas-angelov-dev** [comment]
Information on some of these is available but I will be looking into improving/filling the gaps:
- how it started / why it started etc.
  https://wpemerge.com/2018/10/27/what-is-wp-emerge/
- how does it compare to Timber plugin
  https://docs.wpemerge.com/#/framework/overview?id=comparison-table-%C2%B9-%C2%B2
  https://docs.wpemerge.com/#/starter-theme/overview?id=comparison-table
- how to migrate existing themes or WP websites to wpemerge
  Framework integration is incremental and can be used on existing sites without having to rewrite anything.
  https://docs.wpemerge.com/#/framework/0-to-100-setup

**Comment by stefanos82** [comment]
Thank you for letting me know.

I will start reading all this and hopefully to do something useful with it  :laughing:

**Comment by Epistol** [comment]
I would add that there is no comparison to Wordplate, and that there is no example of what a wpemerge project would look like (best documentation is sometimes examples).

**Comment by atanas-angelov-dev** [comment]
> I would add that there is no comparison to Wordplate

@Epistol I am not familiar with Wordplate but from what I'm seeing it's more of an alternative WordPress setup (akin to Bedrock) than a library/starter theme (although it includes some utility functions and Laravel Mix) so they are a different type of project.
In fact, I'm pretty sure you can require the WP Emerge framework in a Wordplate project to use its routing, middleware, controllers, views etc.

> there is no example of what a wpemerge project would look like

Have you seen the [0-100 setup](https://docs.wpemerge.com/#/framework/0-to-100-setup) guide? It provides some insight into how things work together.
Also you can check out a simple example site [here](https://github.com/atanas-angelov-dev/wpemerge-com-mirror) but keep in mind that it focuses more on the starter theme so it barely uses any of the framework features.

There's obviously more tutorial work to be done but hopefully this can get you started.

**Comment by szepeviktor** [comment]
Please consider adding an architectural overview.

**Comment by atanas-dev** [comment]
Update: With today's release of 0.16.0 there are now two new docs for newcomers:
- [What goes where](https://docs.wpemerge.com/#/starter/theme/what-goes-where)
- [Publishing](https://docs.wpemerge.com/#/starter/publishing)

What blog post topics are being considered for the near future:
- A refresher blog post on how WP Emerge can help your project (recent features, benefits outside of routing etc.)
- Bedrock + WP Emerge step-by-step guide
- ACF + WP Emerge guide
