### ISSUE TITLE
registerAdminAction too restrictive ?

### ISSUE THREAD

**Issue by mickaelperrin** [htmlburger/wpemerge#14]
https://github.com/htmlburger/wpemerge/blob/63e599cf1473d1f281500fab6535bf0e0074be96/src/Kernels/HttpKernel.php#L279-L281

I tried to register a route for a sub-page of `options-general.php` and it didn't work until I commented out the `$pagenow` test.

I don't have sufficient WP experience to know if we simply have to simply test `is_admin` or to provide an extended filtered list of admin pages.

**Comment by atanas-angelov-dev** [comment]
@mickaelperrin thank you for the report.
The issue has been fixed in 63b660d9d7dfb04723924ee8c5c50d74a2440710 and will be included in the next release.
