### ISSUE TITLE
wpemerge breaks autoload outside of WP context

### ISSUE THREAD

**Issue by mickaelperrin** [htmlburger/wpemerge#16]
## Version

_Please add the exact versions used for each of the following:_

  - WP Emerge: latest
  - WordPress: latest
  - PHP: 7.3

## Expected behavior

Calling the autoload outside of WordPress works.

## Actual behavior

Autoload halt the request due to call of `exit`.

## Steps to reproduce (in case of a bug)

  1. Require htmlburger/wpemerge as project wide dependency
  1. Call a script outside of wordpress that requires the `autoload`

## Comments

Related to PR https://github.com/htmlburger/wpemerge/pull/15

**Comment by atanas-angelov-dev** [comment]
Fixed in #15 - thanks!
