### ISSUE TITLE
How to enable flip/whoops?

### ISSUE THREAD

**Issue by galengidman** [htmlburger/wpemerge#17]
The documentation says flip/whoops is used in "development mode" and error views are loaded in production. How do I enable "development mode?" I noticed that whoops is listed as a dev dependency for WP Emerge and isn't even in my vendor folder.

**Comment by atanas-angelov-dev** [comment]
"development mode" is assumed if `WP_DEBUG` is set to true.
Make sure you have development dependencies installed - run `composer install` (it installs development deps by default unless configured otherwise). If whoops is still missing run it again like this:
`composer install --dev`

**Comment by galengidman** [comment]
Duh. I'd tried `WP_DEBUG` already but had a typo in the config file that messed it up. Thanks Atanas.
