### ISSUE TITLE
Theme Stater

### ISSUE THREAD

**Issue by jquimera** [htmlburger/wpemerge#2]
Great job, when will the Theme Starter be ready?

**Comment by atanas-angelov-dev** [comment]
Hi @jquimera ,

The starter theme is mostly done but it's been on the back burner for a while now due to personal reasons.

Hopefully I'll get a beta release done soon *(tm)*.

**Comment by atanas-angelov-dev** [comment]
@jquimera the first public version of the WP Emerge starter theme is now live:
https://github.com/htmlburger/wpemerge-theme
