### ISSUE TITLE
[Question] Twig views templates

### ISSUE THREAD

**Issue by stephanedemotte** [htmlburger/wpemerge#22]
Hello !
First of all, thanks for this great job.

I can't make the twig plugin work.

This is my config

```
// functions.php
use WPEmerge\Facades\WPEmerge;
add_action( 'after_setup_theme', function() {
  WPEmerge::bootstrap( [
    'routes' => [
      'web' => __DIR__ . '/routes/web.php',
    ],
    'providers' => [
      \WPEmergeTwig\View\ServiceProvider::class,
    ],
    'twig' => [
      'views' =>  __DIR__ . '/templates/',
    ],
  ]);
});

```

Got `true` with this.
```
var_dump(file_exists(__DIR__ . '/templates/index.twig'));
```

In my Controllers
```
namespace App\Controllers\Web;

class AppController {

  public function index( $request, $view) {
    return \WPEmerge\view('index.twig');
  }

  public function error( $request, $view) {
    return '404';
  }
}
```

I try a lot of thing, but i always got
`Fatal error: Uncaught Twig\Error\LoaderError: The "/themes/origin/templates/"`

Any idea of what i'm doing wrong ?

Thanks !

**Comment by atanas-dev** [comment]
Hi @stephanedemotte ,

I don't immediately see any error in what you've pasted, no. I suggest clearing the Twig cache directory and possibly debugging the code that throws that exception in order to find what the issue is.

**Comment by stephanedemotte** [comment]
In `src/View/ServiceProvider.php` my setup don't like relative path, i use [roots bedrocks](https://roots.io/bedrock/) to startup my project.

Line 40, i have replace `$relative_views` by `views` and now every things works great.

```
$loader = new Twig_Loader_Filesystem( $views, $root );
``

Don't know why use need relative path, maybe my fix will cause a lot of trouble ?

Thanks.

**Comment by stephanedemotte** [comment]
line 35 you have 
```
$views = array_filter( $views );
```
Maybe you forgot that :)

**Comment by atanas-dev** [comment]
@stephanedemotte did you manage to solve the issue? The `array_filter()` call shouldn't cause any problems - it will just filter out empty/falsy values.

Relative paths are used because the view enginges have a views settings as a base directory to look for views in.
