### ISSUE TITLE
App::flash()->add() doesn't retain existing items

### ISSUE THREAD

**Issue by galengidman** [htmlburger/wpemerge#24]
## Version

  - WP Emerge: 0.16.0
  - WordPress: 5.5.1
  - PHP: 7.4.7

## Expected behavior

`App::flash()->add('errors', 'Error message')`, when run multiple times in a controller method, should add new items to an array accessible by the `errors` key.

## Actual behavior

Instead of adding to existing errors, only the latest error is added.

## Comments

I believe this is due to the `Flash::addToRequest` method always retrieving the existing items in flash via `Flash::get()` vs checking `$request_key` and adding via `Flash::get()` or `Flash::getNext()` depending on the context. I am submitting a PR which has fixed the issue for me.

**Comment by atanas-dev** [comment]
Thank you for the detailed report!
Fixed in c63f6f71ac7f2122a6c39dd63a1be458a4dbaef4.
