### ISSUE TITLE
Can't run php wpemerge install.

### ISSUE THREAD

**Issue by thangpd** [htmlburger/wpemerge#26]
## Version

_Please add the exact versions used for each of the following:_

  - WP Emerge: 0.16.0
  - WordPress: 5.6
  - PHP: 7.3

## Expected behavior

_Please describe the expected behavior here._

## Actual behavior

_Please describe the actual, unexpected behavior here._

## Steps to reproduce (in case of a bug)

  1.
  1.
  1.

## Comments

_Please add any other comments here._

**Comment by atanas-dev** [comment]
Hi @thangpd ,

Please fill in the required fields in the issue template and describe the problem in more detail so that I can investigate - thank you.
