### ISSUE TITLE
Blade engine has problems finding template files

### ISSUE THREAD

**Issue by piotrku** [htmlburger/wpemerge#30]
First thanks for creating this framework, reading the docs it looks like a dreams come true :)

## Version

  - WP Emerge: "htmlburger/wpemerge": "^0.16.0", / "htmlburger/wpemerge-blade": "^0.16.1"
  - WordPress: 5.7.2
  - PHP: 7.4.14

## Expected behavior

my template located at:
`/home/vagrant/code/wp-startup/cms/wp-content/themes/wp-startup/template-cta.blade.php`
i found and treated as a Blade template

## Actual behavior

```
Fatal error: Uncaught Exception: View not found for "template-cta.blade.php"
in /home/vagrant/code/wp-startup/cms/wp-content/themes/wp-startup/vendor/htmlburger/wpemerge/src/View/NameProxyViewEngine.php on line 86

```
## Steps to reproduce (in case of a bug)

  1. I installed wp-merge and followed the steps to create working: https://docs.wpemerge.com/#/framework/0-to-100-setup (it works fine)
  2. Followed steps: https://github.com/htmlburger/wpemerge-blade to add the blade engine (composer + adding \WPEmergeBlade\View\ServiceProvider + used the default options)

## Comments

Please check the attached debugger screenshot - the search paths are really strange - like: `/home/vagrant/code/wp-startup/cms/wp-content/themes/wp-startup/template-cta/blade/php.php`

![image](https://user-images.githubusercontent.com/3919799/121819332-c656d800-cc8c-11eb-8a73-6a8ebf4ebbf6.png)

**Comment by atanas-dev** [comment]
Hi @piotrku ,

This behavior comes from Blade itself rather than WP Emerge or the WP Emerge Blade extension. In Blade, periods are used as directory separators so, when using Blade, instead of specifying `foo/bar/template-cta.blade.php` for a given view use `foo.bar.template-cta` - Blade will automatically convert periods to the appropriate directory separators and will append the file extension.

**Comment by piotrku** [comment]
Thanks, stupid me, too much time spent with WP that I forgot how Blade works :)
