### ISSUE TITLE
View composers don't actually work?

### ISSUE THREAD

**Issue by VesterDe** [htmlburger/wpemerge#4]
## Version

  - WP Emerge: 0.9.2 && 0.9.0
  - WordPress: 4.9.7
  - PHP: 7.2

## Expected behavior

View Composers add variables to a given context.

## Actual behavior

View Composers do not inject any variables into the context.

## Steps to reproduce (in case of a bug)

  1. Install WP Emerge starter theme (bug exists without starter theme as well)
  2. Try to add a ViewComposer to anything
  3. Open the view, which should contain the injected variables
  4. Variable not found.

## Comments

I am getting this behaviour in different contexts. My main project is running Bedrock with not Emerge starter theme, but when I noticed this I made a fresh basic wordpress install and used the Emerge starter theme. In both cases, the behaviour is the same, adding any ViewComposers doesn't affect $context at all.

Adding things normally via ->with and via AddGlobal is fine.

After digging through the code for a while, I noticed 

/vendor/htmlburger/wpemerge/src/View/ViewService.php@compose 

runs a foreach loop over composers and executes them. Since no variables are being passed via reference and this function doesn't return anything, this may be the problem. $context is never affected by the execution of this function.

My quickUglyFix was 
`$context = [];
		foreach ( $composers as $composer ) {
			$context = array_merge($context, $composer->execute( $view ));
		}
		return $context;`

and within //vendor/htmlburger/wpemerge/src/View/PhpView.php I changed line 58 to `$context = View::compose( $composed );`. It then worked as intended.

Now, all of this is really farfetched as an error on your part, so I'm eager to hear what could be the issue.

**Comment by atanas-angelov-dev** [comment]
Hi @VesterDe ,

It seems I've missed to update https://docs.wpemerge.com/view/view-composers.html - composers used to but should no longer return context arrays - instead they should directly interact with the passed $view (e.g. `$view->with( ... )`).
Thanks for bringing this up - I've updated the docs (cache may apply).

PS:
Let me know if you've seen other examples with the older usage anywhere else so I can update that as well.

**Comment by VesterDe** [comment]
Ah, massive headache solved :D

Thanks, I'll keep an eye out.
