### ISSUE TITLE
Feature request: PHP View Engine default template directory

### ISSUE THREAD

**Issue by VesterDe** [htmlburger/wpemerge#5]
Just as it's possible to pass a `'views'` argument to Twig, to reduce the bloat of writing lengthy repeating include statements, could it also be possible to pass a `'views'` argument to the PHP view engine?

It's a detail really, but it would make developing with wpemerge even more pleasant.

**Comment by atanas-angelov-dev** [comment]
View resolution is already relative to the `theme/` directory and `app_partial()` checks for files in the `partials/` directory by default so I'm not sure in which case you can have lengthy include statements.
Can you share an example as I guess I am missing something?

**Comment by VesterDe** [comment]
Well I have templates in `theme/app/templates`, so I could skip `app/templates` that way. 

Like I said, it's a detail.

**Comment by atanas-angelov-dev** [comment]
Finally got to this issue - implemented in 491d5e4e657f2b55cbf429d97b047e9975487903.

Once the next version is released you will be able to specify a `views` key in the configuration which holds an absolute path to a directory that should be checked for views. If a view is not found in the custom directory normal resolution logic will take over.
