### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by appsdevpk** [htmlburger/wpemerge#6]
## Version

  - WP Emerge: 0.9
  - WordPress: 4.9.8
  - PHP: 7.2.7

## Expected behavior

There should be a custom page title

## Actual behavior

The title is Page not found for any custom route like /helloworld etc.

## Steps to reproduce (in case of a bug)

  1. a custom route like Router::get( '/apptest', '\App\Controllers\HomeController@helloWorld');
  2. implement the controller method: public function helloWorld($req,$view){ return app_view( 'templates/helloworld_tpl.php' ); 	}
  3. open the url /apptest in browser.

**Comment by atanas-angelov-dev** [comment]
HI @appsdevpk ,

WP Emerge does not mess with the WP Query so you should rewrite custom URL routes to a URL that WordPress can understand like this:
```
Route::get( '/appptest', ... )
    ->rewrite( 'index.php?page_id=123' );
```

This is essentially a shortcut to [add_rewrite_rule()](https://codex.wordpress.org/Rewrite_API/add_rewrite_rule) without having to specify `$regex` or `$after`. Note that after adding this you should refresh your permalinks.

If you do not want to rewrite urls for some reason, you can override the main WP Query using `query_posts()` inside your controller but this is not advisable and is less efficient.
