### ISSUE TITLE
Feature request: app_partial function that returns instead of echoes

### ISSUE THREAD

**Issue by VesterDe** [htmlburger/wpemerge#7]
Would it be against the general design of this framework to make a new function (let's say) app_partial_s, which is exactly the same as app_partial, but returns the output of the composed View, instead of echoing it?

I want to handle shortcodes within wpemerge, and app_partial can't work in that situation, since it echoes.

I can write the PR, if it's approved.

Edit: To clarify, I can wrap ob_start() around it, but I'd rather not.

**Comment by atanas-angelov-dev** [comment]
It's not really needed - `app_partial()` is an echo-ing shortcut so you can just use what it uses internally:
https://github.com/htmlburger/wpemerge/blob/master/src/functions.php#L79-L83
i.e. this is what you need:
```php
$html = View::make( $views )->with( $context )->toString();
```

**Comment by VesterDe** [comment]
Yeah ok, I saw that, I guess that also an ok option.

Thanks.
